ShopApp/ShopApp.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IyzipayCore;
using IyzipayCore.Model;
using IyzipayCore.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Identity;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private IOrderService _orderService;
        private UserManager<ApplicationUser> _userManager;

        public CartController(IOrderService orderService, ICartService cartService, UserManager<ApplicationUser> userManager)
        {
            _orderService = orderService;
            _cartService = cartService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            if (cart == null)
            {
                return NotFound();
            }
            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (decimal)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };

            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                //Ödeme
                //Sipariş
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserId(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.Product.Id,
                        Name = i.Product.Name,
                        Price = (decimal)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.Id.ToString());
                    return View("Success");
                }
            }

            return View(model);
        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(111111, 999999).ToString();
            order.OrderState = EnumOrderState.Completed; //sipariş durumu
            order.PaymentTypes = EnumPaymentTypes.CreditCart; //ödeme tipi
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };
                order.OrderItems.Add(orderitem);
            }
            _orderService.Create(order);
        }

        private void ClearCart(string cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-8Ut5931cW2vX1kNom04tcwL0JbP5RP4L"; //your api key
            options.SecretKey = "sandbox-nhXj4NubCEByFl3VQJi7go63nn4ZuQPt"; //your secret key
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0]; ;
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0]; ;
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.Cvv;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            //paymentCard.CardHolderName = "John Doe";
            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "Nuri";
            buyer.Surname = "Çetin";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;

            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.Name;
                basketItem.Category1 = "Phone";
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Price = (item.Price * item.Quantity).ToString().Split(",")[0];

                basketItems.Add(basketItem);
            }

            request.BasketItems = basketItems;

            return Payment.Create(request, options);

        }

        public IActionResult GetOrders()
        {
            var orders = _orderService.GetOrders(_userManager.GetUserId(User));
            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;

            foreach (var order in orders)
            {
                orderModel = new OrderListModel();
                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.OrderNote = order.OrderNote;
                orderModel.Phone = order.Phone;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;

ShopApp/ShopApp.WebUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService) //ctor constructor
        {
            _productService = productService;
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product == null)
            {
                return NotFound();
            }

            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList(),
                Brands=product.ProductBrands.Select(i=>i.Brand).FirstOrDefault()
            });;
        }
        public IActionResult List(string category,string brand, int page = 1)
        {
            const int pageSize = 3;
            //return View(_productService.GetAll());
            if (brand!=null)
            {

                return View(new ProductListModel()
                {
                    Products = _productService.GetProductsByBrand(brand, page, pageSize),
                    PageInfo = new PageInfo()
                    {
                        TotalItems = _productService.GetCountByBrand(brand),
                        CurrentPage = page,
                        ItemPerPage = pageSize,
                        CurrentCategory = null,
                        CurrentBrand = brand
                    }
                });
            }
            return View(new ProductListModel()
            {
                Products = _productService.GetProductsByCategory(category, page, pageSize),
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemPerPage = pageSize,
                    CurrentCategory = category,
                    CurrentBrand = null
                }
            }) ;

        }
    }
}

ShopApp/ShopApp.WebUI/ViewComponents/BrandListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.ViewComponents
{
    public class BrandListViewComponent : ViewComponent
    {
        private IBrandService _brandService;
        public BrandListViewComponent(IBrandService brandService)
        {
            _brandService = brandService;
        }
        public IViewComponentResult Invoke()
        {
            return View(new BrandListViewModel()
            {
                SelectedBrand = RouteData.Values["brand"]?.ToString(), //startup MapRoute tan alır. querystring gibi. 
                Brands = _brandService.GetAll()
            });
        }

    }
}

ShopApp/ShopApp.WebUI/Views/Shop/Details.cshtml
@model ProductDetailsModel
@{ ViewData["Title"] = "Details"; }

<div class="row">
    <div class="col-md-3">
        <img src="~/img/@Model.Product.ImageUrl" alt="@Model.Product.Name" class="img-fluid" />
    </div>
    <div class="col-md-9">
        <h1 class="mb-3">
            @Model.Product.Name
        </h1>
        <hr />

        @foreach (var category in Model.Categories)
        {
        <a href="#" class="btn btn-link p-0 mb-3">@category.Name</a>}
    <hr />
        <a href="#" class="btn btn-link p-0 mb-3">@Model.Brands.Name</a>

        <div class="mb-3">
            <h4 class="text-primary mb-3">
                @Model.Product.Price TL
            </h4>

            <form asp-controller="Cart" asp-action="AddToCart" method="post" class="form-inline">
                <input type="hidden" name="productId" value="@Model.Product.Id" />
                <div class="input-group mb-3">
                    <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" style="width:100px;" />
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-cart-plus"></i> Add To Cart
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><b>Ürün Bilgileri</b> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><b>Ürün Yorumları</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"><b>Taksit Seçenekleri</b></a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                <div class="tab_container">
                    <div id="tab-content-1" class="tabPanel" style="display: block;">
                        <div class="panelContent">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <th>  <label asp-for="@Model.Product.Name"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblMarkaAd">@Model.Product.Name</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>  <label asp-for="@Model.Brands.Name"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblMarkaAd">@Model.Brands.Name</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>  <label asp-for="@Model.Product.Model"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblUrunGrupAd">@Model.Product.Model</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>  <label asp-for="@Model.Product.Code"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblUrunKod">@Model.Product.Code</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>  <label asp-for="@Model.Product.Dimensions"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblUrunBoyut">@Model.Product.Dimensions</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th><label asp-for="@Model.Product.SequenceMeter"></label></th>
                                        <td>
                                            <span id="ContentPlaceHolder1_lblUrunM2">@Model.Product.SequenceMeter</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th><label asp-for="@Model.Product.Material"></label></th>
                                        <td>@Model.Product.Material</td>
                                    </tr>
                                    <tr>
                                        <th><label asp-for="@Model.Product.WarrantyPeriod"></label></th>
                                        <td>@Model.Product.WarrantyPeriod YIL</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="panelContent">
                    <div style="margin-bottom: 10px">
                        <span>Bu ürüne ilk yorum yapan siz olun</span>
                    </div>
                    <div class="commentBox">
                        <div class="col-xs-12 col-sm-8">
                            <textarea class="form-control grey commenttextbox" id="tbCommentSubject" required="required" placeholder="Yorum Başlığı" rows="1"></textarea>
                        </div>

                        <div class="col-xs-12 col-sm-8">
                            <textarea class="form-control grey commenttextbox" id="tbComment" required="required" onkeypress="return TextAreaControl(event,this)" placeholder="birincilerhali.com'dan satın aldığınız ürünle ilgili yorum yapıp görüşlerinizi paylaşabilirsiniz.(Not:Yorum yapabilmek için kullanıcı girişi yapmalısınız)" rows="7"></textarea>
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <a class="add-cart-button comment" onclick="DoComment()">Yorumla</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">Tab3</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p class="p-3">
            @Html.Raw(Model.Product.Description)
        </p>
    </div>
</div>

ShopApp/ShopApp.WebUI/Views/Shop/List.cshtml
@model ProductListModel

<div class="row">
    <div class="col-md-3">

        <h3>Kategoriler</h3>
        <ul class="list-group">
            @await Component.InvokeAsync("CategoryList")
        </ul>

        <h3>Markalar</h3>
        <ul class="list-group">
            @await Component.InvokeAsync("BrandList")
        </ul>
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <partial name="_product" for="@product" />
            }
        </div>
        <div page-model="@Model.PageInfo" ></div>
    </div>
</div>